### ISSUE TITLE
Validate shows warning related to libsigar

### ISSUE THREAD

**Issue by garethahealy** [rhq-project/rhq-agent-plugin-plugin#17]
When running the plugin with validate, you get an warning message about native libs not found. The build doesn't fail, but will confuse people.

See: https://gist.github.com/garethahealy/84090bdb6f03aafa4970
Attached example: https://github.com/garethahealy/jon-plugins/blob/master/jon-plugin-native-issue.zip
Original Forum: https://developer.jboss.org/message/917042

**Comment by tsegismont** [comment]
Thanks for the report Gareth!
