### ISSUE TITLE
Validate and Upload have a 'skip' flag, but don't use it

### ISSUE THREAD

**Issue by garethahealy** [rhq-project/rhq-agent-plugin-plugin#18]
Was just quickly looking through the code and noticed validate and Upload have a 'skip' flag, but don't actually do anything other than log it out.

See how deploy returns:
https://github.com/rhq-project/rhq-agent-plugin-plugin/blob/master/src/main/java/org/rhq/maven/plugins/DeployMojo.java#L79

The other two don't:
https://github.com/rhq-project/rhq-agent-plugin-plugin/blob/master/src/main/java/org/rhq/maven/plugins/ValidateMojo.java#L121

https://github.com/rhq-project/rhq-agent-plugin-plugin/blob/master/src/main/java/org/rhq/maven/plugins/UploadMojo.java#L169

Is that correct?

**Comment by tsegismont** [comment]
Nice catch! It's definitely not correct.
